import { TemplateConfig } from '@/types/template';

export const templates: TemplateConfig[] = [
  {
    id: 'instagram-card',
    name: 'Instagram Box Frame',
    description: 'Style viral Instagram dengan frame warna tebal & kotak To/From/Note/Song',
    category: 'Viral IG',
    thumbnail: '#D8000C',
    backgroundColor: '#D8000C',
    backgroundType: 'solid',
    width: 1080,
    height: 1080,
    accentColor: '#17212F',
    titleText: 'MENFESS!!',
    titleStyle: {
      fontFamily: '"Montserrat", "Arial Black", "Arial", sans-serif',
      fontSize: 54,
      color: '#000000',
      alignment: 'center',
      lineHeight: 1.1,
      fontWeight: '900',
      letterSpacing: 4,
    },
    titlePosition: {
      x: 0.5,
      y: 0.25,
      width: 0.8,
      height: 0.08,
    },
    textAreaPosition: {
      x: 0.14,
      y: 0.43,
      width: 0.72,
      height: 0.28,
    },
    textAreaBackground: '#17212F',
    textAreaBorderRadius: 8,
    textStyle: {
      fontFamily: '"Segoe UI", "Arial", sans-serif',
      fontSize: 28,
      color: '#FFFFFF',
      alignment: 'center',
      lineHeight: 1.45,
      fontWeight: 'bold',
    },
    decorations: [],
  },
  {
    id: 'classic-dark',
    name: 'Classic Dark',
    description: 'Hitam / Vintage – Nuansa kertas sobek klasik',
    category: 'Vintage',
    thumbnail: '#1a1a1a',
    backgroundColor: '#111111',
    backgroundType: 'texture',
    width: 1080,
    height: 1080,
    accentColor: '#e8d5b0',
    titleText: 'Cakrawala University',
    titleStyle: {
      fontFamily: '"Georgia", "Times New Roman", serif',
      fontSize: 52,
      color: '#1a1a1a',
      alignment: 'center',
      lineHeight: 1.2,
      fontWeight: 'bold',
      letterSpacing: 6,
    },
    titlePosition: {
      x: 0.5,
      y: 0.18,
      width: 0.75,
      height: 0.1,
    },
    textAreaPosition: {
      x: 0.1,
      y: 0.28,
      width: 0.8,
      height: 0.5,
    },
    textAreaBackground: '#f5f0e8',
    textAreaBorderRadius: 0,
    textStyle: {
      fontFamily: '"Georgia", "Times New Roman", serif',
      fontSize: 28,
      color: '#1a1a1a',
      alignment: 'center',
      lineHeight: 1.6,
    },
    senderStyle: {
      fontFamily: '"Georgia", "Times New Roman", serif',
      fontSize: 20,
      color: '#555555',
      alignment: 'right',
      lineHeight: 1.4,
      fontWeight: 'normal',
    },
    senderPosition: {
      x: 0.1,
      y: 0.81,
      width: 0.8,
      height: 0.06,
    },
    decorations: [
      // Top bar
      {
        type: 'rect',
        x: 0,
        y: 0,
        width: 1080,
        height: 60,
        color: '#e8d5b0',
      },
      // Menfess badge top-left
      {
        type: 'text',
        x: 30,
        y: 38,
        text: 'MENFESS',
        fontFamily: '"Georgia", "Times New Roman", serif',
        fontSize: 14,
        fontWeight: 'bold',
        textColor: '#1a1a1a',
        letterSpacing: 4,
      },
      // Date top-right
      {
        type: 'text',
        x: 1050,
        y: 38,
        text: '★ EDISI KHUSUS ★',
        fontFamily: '"Georgia", "Times New Roman", serif',
        fontSize: 12,
        fontWeight: 'normal',
        textColor: '#555555',
        alignment: 'right',
      },
      // Torn paper effect (top of white area)
      {
        type: 'torn-paper',
        x: 0.1,
        y: 0.27,
        width: 0.8,
        height: 0.54,
        color: '#f5f0e8',
      },
      // Decorative horizontal line below title
      {
        type: 'line',
        x: 0.15,
        y: 0.245,
        width: 0.7,
        height: 0,
        color: '#e8d5b0',
        strokeWidth: 1.5,
      },
      // Bottom bar
      {
        type: 'rect',
        x: 0,
        y: 1020,
        width: 1080,
        height: 60,
        color: '#e8d5b0',
      },
      // Bottom text
      {
        type: 'text',
        x: 540,
        y: 1053,
        text: '— MENFESS STUDIO —',
        fontFamily: '"Georgia", "Times New Roman", serif',
        fontSize: 13,
        fontWeight: 'normal',
        textColor: '#1a1a1a',
        alignment: 'center',
        letterSpacing: 3,
      },
    ],
  },
  {
    id: 'blue-sky-glass',
    name: 'Blue Sky Glass',
    description: 'Biru / Modern – Efek kaca transparan',
    category: 'Modern',
    thumbnail: '#1e40af',
    backgroundColor: '#0f172a',
    backgroundType: 'gradient',
    gradientColors: ['#0f172a', '#1e3a5f', '#0c4a6e'],
    width: 1080,
    height: 1080,
    accentColor: '#38bdf8',
    titleText: 'SUARA HATI',
    titleStyle: {
      fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif',
      fontSize: 48,
      color: '#ffffff',
      alignment: 'center',
      lineHeight: 1.2,
      fontWeight: '700',
      letterSpacing: 8,
    },
    titlePosition: {
      x: 0.5,
      y: 0.16,
      width: 0.8,
      height: 0.1,
    },
    textAreaPosition: {
      x: 0.1,
      y: 0.28,
      width: 0.8,
      height: 0.52,
    },
    textAreaBackground: 'rgba(255,255,255,0.08)',
    textAreaBorderRadius: 24,
    textStyle: {
      fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif',
      fontSize: 28,
      color: '#f0f9ff',
      alignment: 'center',
      lineHeight: 1.65,
    },
    senderStyle: {
      fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif',
      fontSize: 18,
      color: '#7dd3fc',
      alignment: 'right',
      lineHeight: 1.4,
      fontWeight: '500',
    },
    senderPosition: {
      x: 0.1,
      y: 0.83,
      width: 0.8,
      height: 0.06,
    },
    decorations: [
      // Top glow circle
      {
        type: 'badge',
        x: 540,
        y: 120,
        width: 320,
        height: 320,
        color: 'rgba(56,189,248,0.08)',
        opacity: 1,
      },
      // Decorative thin top line
      {
        type: 'line',
        x: 0.2,
        y: 0.105,
        width: 0.6,
        height: 0,
        color: 'rgba(56,189,248,0.5)',
        strokeWidth: 1,
      },
      // Tagline
      {
        type: 'text',
        x: 540,
        y: 96,
        text: 'M E N F E S S',
        fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif',
        fontSize: 13,
        fontWeight: '600',
        textColor: '#38bdf8',
        alignment: 'center',
        letterSpacing: 6,
      },
      // Glass border
      {
        type: 'rect',
        x: 108,
        y: 302,
        width: 864,
        height: 562,
        color: 'transparent',
        strokeWidth: 1,
        strokeColor: 'rgba(56,189,248,0.25)',
        borderRadius: 24,
      },
      // Bottom accent line
      {
        type: 'line',
        x: 0.3,
        y: 0.905,
        width: 0.4,
        height: 0,
        color: 'rgba(56,189,248,0.4)',
        strokeWidth: 1,
      },
      // Bottom text
      {
        type: 'text',
        x: 540,
        y: 1020,
        text: 'MENFESS STUDIO',
        fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif',
        fontSize: 12,
        fontWeight: '500',
        textColor: 'rgba(255,255,255,0.3)',
        alignment: 'center',
        letterSpacing: 4,
      },
    ],
  },
  {
    id: 'white-minimal',
    name: 'White Minimal',
    description: 'Putih / Minimalis – Bersih dan elegan',
    category: 'Minimalis',
    thumbnail: '#f8f8f5',
    backgroundColor: '#faf9f6',
    backgroundType: 'solid',
    width: 1080,
    height: 1080,
    accentColor: '#7c1d1d',
    titleText: 'PESAN RAHASIA',
    titleStyle: {
      fontFamily: '"Georgia", "Times New Roman", serif',
      fontSize: 44,
      color: '#1a1a1a',
      alignment: 'center',
      lineHeight: 1.2,
      fontWeight: 'bold',
      letterSpacing: 4,
    },
    titlePosition: {
      x: 0.5,
      y: 0.17,
      width: 0.75,
      height: 0.09,
    },
    textAreaPosition: {
      x: 0.12,
      y: 0.3,
      width: 0.76,
      height: 0.48,
    },
    textAreaBackground: '#ffffff',
    textAreaBorderRadius: 4,
    textStyle: {
      fontFamily: '"Georgia", "Times New Roman", serif',
      fontSize: 28,
      color: '#2c2c2c',
      alignment: 'center',
      lineHeight: 1.7,
    },
    senderStyle: {
      fontFamily: '"Georgia", "Times New Roman", serif',
      fontSize: 18,
      color: '#7c1d1d',
      alignment: 'right',
      lineHeight: 1.4,
      fontWeight: 'normal',
    },
    senderPosition: {
      x: 0.12,
      y: 0.81,
      width: 0.76,
      height: 0.06,
    },
    decorations: [
      // Top maroon accent bar (thin)
      {
        type: 'rect',
        x: 0,
        y: 0,
        width: 1080,
        height: 6,
        color: '#7c1d1d',
      },
      // Logo area
      {
        type: 'text',
        x: 540,
        y: 70,
        text: 'MENFESS',
        fontFamily: '"Georgia", "Times New Roman", serif',
        fontSize: 13,
        fontWeight: 'bold',
        textColor: '#7c1d1d',
        alignment: 'center',
        letterSpacing: 6,
      },
      // Decorative line under title
      {
        type: 'line',
        x: 0.35,
        y: 0.235,
        width: 0.3,
        height: 0,
        color: '#7c1d1d',
        strokeWidth: 1.5,
      },
      // Outer border rect
      {
        type: 'rect',
        x: 40,
        y: 40,
        width: 1000,
        height: 1000,
        color: 'transparent',
        strokeWidth: 1,
        strokeColor: '#e8e5de',
        borderRadius: 0,
      },
      // Inner border
      {
        type: 'rect',
        x: 50,
        y: 50,
        width: 980,
        height: 980,
        color: 'transparent',
        strokeWidth: 0.5,
        strokeColor: '#d4cfc4',
        borderRadius: 0,
      },
      // Text area subtle border
      {
        type: 'rect',
        x: 130,
        y: 324,
        width: 820,
        height: 518,
        color: 'transparent',
        strokeWidth: 1,
        strokeColor: '#e8e5de',
        borderRadius: 4,
      },
      // Bottom maroon line
      {
        type: 'line',
        x: 0.35,
        y: 0.9,
        width: 0.3,
        height: 0,
        color: '#7c1d1d',
        strokeWidth: 1,
      },
      // Bottom text
      {
        type: 'text',
        x: 540,
        y: 1020,
        text: 'MENFESS STUDIO',
        fontFamily: '"Georgia", "Times New Roman", serif',
        fontSize: 11,
        fontWeight: 'normal',
        textColor: '#aaa',
        alignment: 'center',
        letterSpacing: 4,
      },
      // Bottom maroon accent
      {
        type: 'rect',
        x: 0,
        y: 1074,
        width: 1080,
        height: 6,
        color: '#7c1d1d',
      },
    ],
  },
];

export const getTemplateById = (id: string): TemplateConfig | undefined => {
  return templates.find((t) => t.id === id);
};
